# Generated by Django 2.2.10 on 2020-03-22 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='is_f2p',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_f2p',
        ),
        migrations.AddField(
            model_name='hero',
            name='f2p_level',
            field=models.CharField(choices=[('F_01_STORY', 'Story'), ('F_02_THREE_STARS_STANDARD', '3* Standard Pool'), ('F_03_THREE_STARS_LIMITED', '3* Limited Pool'), ('F_04_FOUR_STARS_STANDARD', '4* Standard Pool'), ('F_06_GRAIL', 'Grail'), ('F_05_FOUR_STARS_LIMITED', '4* Limited Pool'), ('F_08_FIVE_STARS_STANDARD', '3* Standard Pool'), ('F_09_FIVE_STARS_LIMITED', '3* Standard Pool')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='f2p_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('COLORLESS', 'Colorless')], max_length=15), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='gamepedia_url',
            field=models.URLField(default='https://poro.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='rarity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
