# Generated by Django 2.2.10 on 2020-03-22 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0002_auto_20200322_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='f2p_level',
            field=models.CharField(choices=[('F_01_STORY', 'Story'), ('F_02_THREE_STARS_STANDARD', '3* Standard Pool'), ('F_03_THREE_STARS_LIMITED', '3* Limited Pool'), ('F_04_FOUR_STARS_STANDARD', '4* Standard Pool'), ('F_06_GRAIL', 'Grail'), ('F_05_FOUR_STARS_LIMITED', '4* Limited Pool'), ('F_08_FIVE_STARS_STANDARD', '3* Standard Pool'), ('F_09_FIVE_STARS_LIMITED', '3* Standard Pool')], max_length=25),
        ),
        migrations.AlterField(
            model_name='skill',
            name='f2p_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('F_01_STORY', 'Story'), ('F_02_THREE_STARS_STANDARD', '3* Standard Pool'), ('F_03_THREE_STARS_LIMITED', '3* Limited Pool'), ('F_04_FOUR_STARS_STANDARD', '4* Standard Pool'), ('F_06_GRAIL', 'Grail'), ('F_05_FOUR_STARS_LIMITED', '4* Limited Pool'), ('F_08_FIVE_STARS_STANDARD', '3* Standard Pool'), ('F_09_FIVE_STARS_LIMITED', '3* Standard Pool')], max_length=25), size=None),
        ),
    ]
