# Generated by Django 2.2.10 on 2020-03-23 03:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0004_auto_20200322_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='heroes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
