# Generated by Django 2.2.10 on 2020-03-23 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feh", "0005_auto_20200323_0345"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="boonbanes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=3),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
