# Generated by Django 2.2.10 on 2020-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feh", "0007_auto_20200330_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
