# Generated by Django 2.2.10 on 2020-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feh", "0015_auto_20200419_0901"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="has_resplendent",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
