# Generated by Django 2.2.10 on 2020-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0016_hero_has_resplendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='season',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
