# Generated by Django 2.2.10 on 2020-09-12 18:32

from django.db import migrations, models
import linus.feh.models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0018_hero_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=linus.feh.models.upload_to_dir),
        ),
    ]
