# Generated by Django 2.2.10 on 2021-02-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0019_auto_20200912_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='icon_image',
        ),
    ]
