# Generated by Django 3.0.14 on 2022-09-28 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0022_auto_20210401_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='availability',
            field=models.CharField(choices=[('A_STANDARD', 'Standard Pool'), ('A_SPECIAL', 'Special'), ('A_GHB', 'Grand Hero Battle'), ('A_TT', 'Tempest Trials'), ('A_LEGENDARY', 'Legendary'), ('A_MYTHIC', 'Mythic'), ('A_STORY', 'Story'), ('A_DUO', 'Duo'), ('A_HARMONIZED', 'Harmonized'), ('A_ASCENDANT', 'Ascendant')], max_length=15),
        ),
        migrations.AlterField(
            model_name='hero',
            name='f2p_level',
            field=models.CharField(choices=[('F_00', 'Story'), ('F_01', 'Grail'), ('F_02', '3* Standard Pool'), ('F_03', '4* Standard Pool'), ('F_04', '5* Standard Pool'), ('F_07', '3* Limited Pool'), ('F_08', '4* Limited Pool'), ('F_09', '5* Limited Pool')], max_length=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='origin_game',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), size=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='stripped_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='availabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A_STANDARD', 'Standard Pool'), ('A_SPECIAL', 'Special'), ('A_GHB', 'Grand Hero Battle'), ('A_TT', 'Tempest Trials'), ('A_LEGENDARY', 'Legendary'), ('A_MYTHIC', 'Mythic'), ('A_STORY', 'Story'), ('A_DUO', 'Duo'), ('A_HARMONIZED', 'Harmonized'), ('A_ASCENDANT', 'Ascendant')], max_length=15), size=None),
        ),
        migrations.AlterField(
            model_name='skill',
            name='f2p_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('F_00', 'Story'), ('F_01', 'Grail'), ('F_02', '3* Standard Pool'), ('F_03', '4* Standard Pool'), ('F_04', '5* Standard Pool'), ('F_07', '3* Limited Pool'), ('F_08', '4* Limited Pool'), ('F_09', '5* Limited Pool')], max_length=25), size=None),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stripped_name',
            field=models.CharField(max_length=200),
        ),
    ]
