name: Nino reading exercises

on:
  schedule:
    - cron: '5 4 * * 3'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NINO_BOOKS }}
          fetch-depth: 0

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Nino
          author_email: nino@blackfang.com
          commit: --allow-empty
          message: 'Weekly automated update'
        env:
          GITHUB_TOKEN: ${{ secrets.NINO_BOOKS }}
