# This is a basic workflow to help you get started with Actions

name: Nino reading exercises

# Controls when the workflow will run
on:
  schedule:
    # This will run the workflow at 4:05 AM every Wednesday
    - cron: '5 4 * * 3'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "commit"
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Conditional to ensure job runs only on the 'main' branch
    if: github.ref == 'refs/heads/main'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NINO_BOOKS }}

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          author_name: Nino
          author_email: nino@blackfang.com
          commit: --allow-empty
          message: 'Weekly automated update'
